if has("syntax")
  syntax on
endif

set t_Co=256 " 256 color term
set background=dark
syntax on
set number ruler
let g:molokai_original = 2
color molokai
hi ColorColumn ctermbg=lightgrey guibg=lightgrey


" General
set nocompatible " With vi
filetype plugin indent on
set autochdir " Change into file's dir.
set fileformats=unix,dos,mac " Support all, prefer unix
set hidden 
"
set nobackup
set nowritebackup
set noswapfile
"set textwidth=80 " 80 chars per line
"set colorcolumn=+1 " 80 char mark
"set linebreak " Break lines after 80 chars at logical points
set wrap " And otherwise always
set number " Line numbers
set numberwidth=5 " 99999 lines max
set showmatch " Matching braces
set cursorline

"To have vim auto jump to where we were when we last closed it
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd		" Show (partial) command in status line.
"set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden             " Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)
"For templates:
if has("autocmd")
 autocmd bufnewfile *.c so /home/koen/.vim/templates/c_header
 autocmd bufnewfile *.c exe "1," . 8 . "g/File Name:.*/s//File Name: " .expand("%")
 autocmd bufnewfile *.c exe "1," . 8 . "g/Creation Date:.*/s//Creation Date: " .strftime("%d-%m-%Y")
 autocmd Bufwritepre,filewritepre *.c execute "normal ma"
 " autocmd Bufwritepre,filewritepre *.c exe "1," . 8 . "g/Last Modified:.*/s/Last Modified:.*/Last Modified : " .strftime("%c")
 autocmd bufwritepost,filewritepost *.c execute "normal `a"
endif


set smarttab
set expandtab
set autoindent
set smartindent
set backspace=2
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Smart home
map <khome> <home>
nmap <khome> <home>
inoremap <silent> <home> <C-O>:call Home()<CR>
nnoremap <silent> <home> :call Home()<CR>
function! Home()
        let curcol = wincol()
        normal ^
        let newcol = wincol()
        if newcol == curcol
             normal 0
        endif
endfunction

map <F3> :tabp<cr>
map <F4> :tabn<cr>
map <F5> <esc>:TlistToggle<cr>
map <C-S> <esc>:w<cr>
map <F6> <Plug>TaskList
filetype plugin on
autocmd FileType python set omnifunc=pythoncomplete#Complete
imap <C-BS> <C-W>

let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplModSelTarget = 1

" For the doxygen:
let g:DoxygenToolkit_authorName="K-4U" 


" This is for highlighting 80+chars
highlight OverLength ctermbg=52 ctermfg=white guibg=#610B0B
match OverLength /\%81v.\+/


" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

